import React from 'react'
import { Document, Page, Text, View, StyleSheet, Image, renderToBuffer } from '@react-pdf/renderer'
import type { Settings, InvoiceItem } from '@/types'

export interface DeliveryOrderData {
  delivery_order_id: string
  customer_name: string
  customer_address: string
  delivery_date: string
  notes: string
  items: InvoiceItem[]
}

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: 'Helvetica', color: '#1a1a1a' },
  header: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 30 },
  logo: { width: 80, height: 40, objectFit: 'contain' },
  companyName: { fontSize: 20, fontFamily: 'Helvetica-Bold', marginBottom: 4 },
  companyInfo: { fontSize: 9, color: '#666', lineHeight: 1.4 },
  doTitle: { fontSize: 24, fontFamily: 'Helvetica-Bold', color: '#333', textAlign: 'right' },
  doNumber: { fontSize: 12, color: '#666', textAlign: 'right', marginTop: 4 },
  section: { marginBottom: 20 },
  sectionTitle: { fontSize: 11, fontFamily: 'Helvetica-Bold', marginBottom: 8, borderBottomWidth: 1, borderBottomColor: '#e5e7eb', paddingBottom: 4 },
  table: { marginTop: 10 },
  tableHeader: { flexDirection: 'row', backgroundColor: '#f3f4f6', padding: '6 8', fontFamily: 'Helvetica-Bold' },
  tableRow: { flexDirection: 'row', padding: '5 8', borderBottomWidth: 1, borderBottomColor: '#f3f4f6' },
  col1: { flex: 3 },
  col2: { flex: 1, textAlign: 'right' },
  col3: { flex: 1, textAlign: 'right' },
  notes: { marginTop: 20, padding: 12, backgroundColor: '#f9fafb', borderRadius: 4 },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, textAlign: 'center', color: '#999', fontSize: 8 },
})

function DeliveryPDF({ order, settings }: { order: DeliveryOrderData; settings: Settings }) {
  return React.createElement(Document, null,
    React.createElement(Page, { size: 'A4', style: styles.page },
      // Header
      React.createElement(View, { style: styles.header },
        React.createElement(View, null,
          settings.logo_url
            ? React.createElement(Image, { src: settings.logo_url, style: styles.logo })
            : React.createElement(Text, { style: styles.companyName }, settings.company_name || 'FloorHub'),
          settings.logo_url && React.createElement(Text, { style: { ...styles.companyName, marginTop: 4 } }, settings.company_name || 'FloorHub'),
          React.createElement(Text, { style: styles.companyInfo }, settings.company_address || ''),
          React.createElement(Text, { style: styles.companyInfo }, settings.company_phone || ''),
          React.createElement(Text, { style: styles.companyInfo }, settings.company_email || ''),
        ),
        React.createElement(View, null,
          React.createElement(Text, { style: styles.doTitle }, 'DELIVERY ORDER'),
          React.createElement(Text, { style: styles.doNumber }, order.delivery_order_id),
          order.delivery_date && React.createElement(Text, { style: { ...styles.doNumber, marginTop: 4 } }, `Delivery Date: ${order.delivery_date}`),
        ),
      ),
      // Deliver To
      React.createElement(View, { style: styles.section },
        React.createElement(Text, { style: styles.sectionTitle }, 'Deliver To'),
        React.createElement(Text, { style: { fontFamily: 'Helvetica-Bold', marginBottom: 2 } }, order.customer_name),
        order.customer_address && React.createElement(Text, { style: styles.companyInfo }, order.customer_address),
      ),
      // Items table (no pricing)
      React.createElement(View, { style: styles.table },
        React.createElement(Text, { style: styles.sectionTitle }, 'Items'),
        React.createElement(View, { style: styles.tableHeader },
          React.createElement(Text, { style: styles.col1 }, 'Product'),
          React.createElement(Text, { style: styles.col2 }, 'Sq Ft'),
          React.createElement(Text, { style: styles.col3 }, 'Boxes'),
        ),
        ...order.items.map((item, i) =>
          React.createElement(View, { key: i, style: styles.tableRow },
            React.createElement(Text, { style: styles.col1 }, item.product_name),
            React.createElement(Text, { style: styles.col2 }, Number(item.sqft_needed).toFixed(2)),
            React.createElement(Text, { style: styles.col3 }, String(item.boxes_needed)),
          )
        ),
      ),
      // Notes
      order.notes ? React.createElement(View, { style: styles.notes },
        React.createElement(Text, { style: { fontFamily: 'Helvetica-Bold', marginBottom: 4 } }, 'Notes'),
        React.createElement(Text, { style: { color: '#666', lineHeight: 1.5 } }, order.notes),
      ) : null,
      // Footer
      React.createElement(Text, { style: styles.footer }, `Generated by FloorHub • ${order.delivery_order_id}`),
    )
  )
}

export async function generateDeliveryPDF(order: DeliveryOrderData, settings: Settings): Promise<Buffer> {
  const element = DeliveryPDF({ order, settings })
  const buffer = await renderToBuffer(element)
  return buffer
}
